services:
    app:
        build:
            context: . # Project root directory
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
            ENV: production
        depends_on:
            - database

    database:
        image: postgres:17-alpine
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
